### ISSUE TITLE
Replace STDOUT with proper Logging

### ISSUE THREAD

**Issue by lost-illusi0n** [lost-illusi0n/lostorm#1]
Seeing ugly STDOUT messages that are not easily removed is not a nice feature. Would be great to replace these printlns with proper logging.

**Comment by DeMack** [comment]
Hey there, @lost-illusi0n, I can help you out with this, if you want to assign this issue to me. Did you have any particular logging framework in mind you'd like to use?

**Comment by lost-illusi0n** [comment]
If you could use something standard like Log4j that'd be great, other than that there should be no real issue. Thank you for reaching out, I'll assign you.
