### ISSUE TITLE
Add Converter Functionality

### ISSUE THREAD

**Issue by lost-illusi0n** [lost-illusi0n/lostorm#2]
A Converter would be able to convert values to and from SQL-friendly values and any other Class. This would require a refactor of the annotation processor as it is not exactly the cleanest module. A converter would be specified to a field by adding a ValueConverter annotation which references a KClass of a converter.
Example
```kotlin
@EntityDataClass
data class Foo(
    @ValueConverter(ComplexValueConverter::class)
    val complexValue: ComplexValue
)

class ComplexValue(val value: Long, val valueLength: Int)

class ComplexValueConverter: Converter<Long, ComplexValue> {
    override fun convertTo(value: Long): ComplexValue = ComplexValue(value, value.toString().length)

    override fun convertFrom(from: ComplexValue): Long = from.value
}
```

**Comment by DeMack** [comment]
I'll take this one on next.

**Comment by lost-illusi0n** [comment]
That'd be great, however I already started on rewriting the annotation processor. If you would like once I resolve this you could take on #3 as with the refactor it should be much easier to implement.

**Comment by DeMack** [comment]
Sounds good. I'll grab that one.

**Comment by lost-illusi0n** [comment]
added by #5
